# Generated by Django 5.2.4 on 2025-08-11 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_initial'),
        ('groups', '0002_initial'),
        ('loans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChamaGroup',
            new_name='Group',
        ),
    ]
