# Generated by Django 5.2.4 on 2025-08-11 16:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_rename_chamagroup_group'),
        ('loans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoanRequest',
            new_name='Loan',
        ),
    ]
