# Generated by Django 5.2.17 on 2026-09-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_alter_group_created_by_and_more"),
        ("loans", "0003_rename_loanrequest_loan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"ordering": ["-requested_on"]},
        ),
        migrations.AlterField(
            model_name="loan",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
