# Generated by Django 5.2.17 on 2026-09-09 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contributions", "0003_initial"),
        ("groups", "0004_alter_group_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="contribution",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions",
                to="groups.group",
            ),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contributions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
